CREATE TABLE Registration
(
	[Username] NVARCHAR(50) NOT NULL PRIMARY KEY, 
    [DateOfBirth] NVARCHAR(100) NOT NULL, 
    [EmailAddress] NVARCHAR(100) NOT NULL, 
    [Password] NVARCHAR(100) NOT NULL, 
    [ConfirmPassword] NVARCHAR(100) NOT NULL
CONSTRAINT [PK_Registration] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, _
IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
